// Golden parity tests: TS observation encoding vs py_reference env._obs().
// Fixtures generated by scripts/make_golden.py from seeded reference games.
import { describe, it, expect } from 'vitest';
import golden from '../services/agent/__fixtures__/golden.json';
import { encodeObs, legalMask, N_OBS_PLANES } from './obs';
import { BOARD_CELLS, type GameState, type Player } from './types';

interface Fixture {
  name: string;
  state: {
    cells: number[];
    stones: number[];
    currentPlayer: number;
    phase: number; // 0=STONE 1=CELL
    remainingK: number;
    lastStonePos: number | null;
    thisTurnCells: number[];
  };
  obsChw: number[];
  legalIdx: number[];
  policy: number[];
  value: number;
  wdl: number[];
}

const fixtures = golden as Fixture[];

function toState(f: Fixture): GameState {
  return {
    cells: Uint8Array.from(f.state.cells),
    stones: Uint8Array.from(f.state.stones),
    currentPlayer: f.state.currentPlayer as Player,
    phase: f.state.phase === 0 ? 'STONE' : 'CELL',
    remainingK: f.state.remainingK,
    lastStonePos: f.state.lastStonePos,
    thisTurnCells: [...f.state.thisTurnCells],
    lastCellPositions: [],
    winner: null,
    winLine: null,
  };
}

describe('golden obs parity', () => {
  it('has fixtures covering both phases', () => {
    expect(fixtures.length).toBeGreaterThanOrEqual(8);
    expect(fixtures.some((f) => f.state.phase === 1)).toBe(true);
  });

  for (const f of fixtures) {
    it(`obs matches exactly — ${f.name}`, () => {
      const obs = encodeObs(toState(f));
      expect(obs.length).toBe(N_OBS_PLANES * BOARD_CELLS);
      expect(f.obsChw.length).toBe(obs.length);
      for (let i = 0; i < obs.length; i++) {
        if (Math.abs(obs[i] - f.obsChw[i]) > 1e-6) {
          const ch = Math.floor(i / BOARD_CELLS);
          const cell = i % BOARD_CELLS;
          expect.fail(
            `${f.name}: plane ${ch} pos ${cell} — ts=${obs[i]} py=${f.obsChw[i]}`,
          );
        }
      }
    });

    it(`legal mask matches — ${f.name}`, () => {
      const mask = legalMask(toState(f));
      const idx: number[] = [];
      for (let i = 0; i < mask.length; i++) if (mask[i]) idx.push(i);
      expect(idx).toEqual(f.legalIdx);
    });
  }

  it('crafted_black_four: completion planes flag both winning extensions', () => {
    const f = fixtures.find((x) => x.name === 'crafted_black_four')!;
    const obs = encodeObs(toState(f));
    // white to move → black's completions are plane 9 (opponent), at (7,3) and (7,8)
    const plane9 = 9 * BOARD_CELLS;
    expect(obs[plane9 + 7 * 15 + 3]).toBe(1);
    expect(obs[plane9 + 7 * 15 + 8]).toBe(1);
    // white has no completions (plane 8 all zero)
    const plane8 = 8 * BOARD_CELLS;
    for (let i = 0; i < BOARD_CELLS; i++) expect(obs[plane8 + i]).toBe(0);
  });
});
